services:
  django:
    container_name: prod-django
    image: ghcr.io/doughflow/doughflow/django:main
    command: gunicorn django_server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django:/app
    env_file:
      - ./django/.secrets # Specify the path to your .env file

  nginx:
    container_name: prod-nginx
    image: ghcr.io/doughflow/doughflow/nginx:main
    depends_on:
      - django
      - next

  next:
    container_name: prod-next
    image: ghcr.io/doughflow/doughflow/nextjs:main
    hostname: nextjs
