services:
  django:
    container_name: prod-django
    build: ./django
    command: gunicorn django_server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./django/.secrets # Specify the path to your .env file

  nginx:
    container_name: prod-nginx
    build: ./nginx
    volumes:
      - static_volume:/home/staticfiles
      - media_volume:/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
