version: "3.8"

services:
  django:
    container_name: df-dev-frontend-django
    build: ./django
    command: gunicorn django_server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env # Specify the path to your .env file
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: df-dev-frontend-nginx
    build: ./nginx
    volumes:
      - static_volume:/home/staticfiles
      - media_volume:/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - frontend

  frontend:
    container_name: df-dev-frontend-frontend
    build: ./next
    ports:
      - "3000:3000" # Assuming your frontend runs on port 3000
    hostname: nextjs

  db:
    container_name: df-dev-frontend-db
    image: postgres:16
    env_file:
      - .env # Specify the path to your .env file
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 15s
      timeout: 60s
      retries: 3
      start_period: 10s
    ports:
      - "5432:5432" # Mapping PostgreSQL port to the host
volumes:
  static_volume:
  media_volume:
