version: "3.8"

services:
    nginx:
        image: nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - django
   
    django:
        build:
            context: ./django
            dockerfile: Dockerfile
        ports:
          - "8000:8000"
        volumes:
          - ./django:/app
