version: "3.8"

services:
    django:
        build:
            context: ./django
            dockerfile: Dockerfile
        ports:
          - "8000:8000"
        volumes:
          - ./django:/app
