# Generated by Django 4.1.13 on 2024-02-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockMarketData",
            fields=[
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("ticker", models.CharField(max_length=25)),
                ("open", models.DecimalField(decimal_places=2, max_digits=10)),
                ("high", models.DecimalField(decimal_places=2, max_digits=10)),
                ("low", models.DecimalField(decimal_places=2, max_digits=10)),
                ("close", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.IntegerField()),
            ],
            options={
                "db_table": "stock_data",
            },
        ),
    ]
