# Generated by Django 5.0.4 on 2024-05-08 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndicatorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateField()),
                ('ticker', models.CharField(max_length=8)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rsi', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
            ],
            options={
                'db_table': 'validated_data',
                'unique_together': {('timestamp', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='StockMarketData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateField()),
                ('ticker', models.CharField(max_length=8)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
                ('candle_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_data',
                'unique_together': {('timestamp', 'ticker')},
            },
        ),
    ]
