# Generated by Django 4.1.13 on 2024-03-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockmarketdata",
            old_name="close",
            new_name="close_price",
        ),
        migrations.RenameField(
            model_name="stockmarketdata",
            old_name="high",
            new_name="high_price",
        ),
        migrations.RenameField(
            model_name="stockmarketdata",
            old_name="low",
            new_name="low_price",
        ),
        migrations.RenameField(
            model_name="stockmarketdata",
            old_name="open",
            new_name="open_price",
        ),
        migrations.AddField(
            model_name="stockmarketdata",
            name="candleTime",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
