# Generated by Django 5.0.2 on 2024-03-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarketdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
