# Generated by Django 5.0.4 on 2024-04-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_stockmarketdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarketdata',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
