- hosts: ec2

  become: yes
  tasks:
    - name: Update Packages
      yum:
        name: "*"
        state: latest
        update_only: yes

    - name: Install Extra Packages
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - python-pip
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - git
          - cronie

    - name: Install Docker
      yum:
        name: docker
        state: latest
        update_cache: yes

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Add User to Docker Group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start and Enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Start and Enable Cron
      systemd:
        name: crond
        state: started
        enabled: yes

    - name: Install Python Packages
      pip:
        name: "{{ packages }}"
      vars:
        packages:
          - boto3
          - urllib3

    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

    - name: Clone DoughFlow Repo
      git:
        repo: https://github.com/DoughFlow/DoughFlow.git
        dest: /home/ec2-user/DoughFlow
        version: main
        force: yes

    - name: Insert Django Secrets
      shell: |
        cd /home/ec2-user/DoughFlow
        /home/ec2-user/DoughFlow/configure_cache.sh --access-key {{ access_key }} --secret-key {{ secret_key }} --secret-name {{ secret_name }}
      ignore_errors: true

    - name: Ensure proxy Folder Exists
      file:
        path: /home/ec2-user/proxy
        state: directory

    - name: Download NGINX Proxy Manager
      shell: aws s3 cp --recursive s3://doughflow-npm-config /home/ec2-user/proxy/

    - name: Cron Job for Keeping NPM Config in S3
      cron:
        name: "NPM S3 Sync"
        user: "ec2-user"
        minute: 0
        hour: 1
        job: "aws s3 cp --recursive /home/ec2-user/proxy/ s3://doughflow-npm-config"

    - name: Start DoughFlow Stack
      shell: |
        cd /home/ec2-user/DoughFlow
        docker-compose up -d

    - name: Start NGINX Proxy Manager
      shell: |
        cd /home/ec2-user/proxy
        docker-compose up -d
