name: Ansible Deploy

on:
  workflow_run:
    workflows: ["Deploy Images to GHCR"]
    types:
      - completed
  workflow_dispatch:

jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yaml
          directory: ansible/
          configuration: |
            [defaults]
            callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
            stdout_callback = yaml
            nocows = false
          key: ${{secrets.SSH_KEY}}
          inventory: |
            [ec2]
            prod_app ansible_host=${{vars.EC2_IP_ADDRESS}} ansible_user=ec2-user
          options: |
            --verbose
            --ssh-extra-args "-o StrictHostKeyChecking=no"
            --extra-vars "access_key=${{secrets.AWS_ACCESS_KEY}} secret_key=${{secrets.AWS_SECRET_KEY}} secret_name=${{secrets.AWS_SECRET_NAME}}"
