name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
      Nginx-Image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './nginx'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: 'Extract metadata for Docker'
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ env.REGISSTRY }}/nginx

          - name: 'Build Nginx Image'
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}    

      Django-Image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './django'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: 'Extract metadata for Docker'
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ env.REGISSTRY }}/django

          - name: 'Build Django Image'
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
