name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-nginx-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './nginx'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.CONTAINER_REGISTRY_KEY}}

          - name: 'Build Nginx Image'
            run: |
              docker build . --tag ghcr.io/messerli-wallace/doughflow-nginx:latest
              docker push ghcr.io/messerli-wallace/doughflow-nginx:latest
      push-django-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './django'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to Github Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.CONTAINER_REGISTRY_KEY}}

          - name: 'Build Django Image'
            run: |
              docker build . --tag ghcr.io/messerli-wallace/doughflow-django:latest
              docker push ghcr.io/messerli-wallace/doughflow-django:latest
