name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      Nginx-Image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './nginx'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            run: echo ${{ secrets.CONTAINER_REGISTRY_KEY }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin

          - name: 'Build Nginx Image'
            run: docker build -t docker.pkg.github.com/messerli-wallace/doughflow/nginx:latest

          - name: 'Push Nginx Image'
            if: github.ref == 'refs/heads/main' && github.event_name == 'push'
            run: docker push docker.pkg.github.com/messerli-wallace/doughflow/nginx:latest

      Django-Image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './django'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            run: echo ${{ secrets.CONTAINER_REGISTRY_KEY }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin

          - name: 'Build Django Image'
            run: docker build -t docker.pkg.github.com/messerli-wallace/doughflow/django:latest

          - name: 'Push Django Image'
            if: github.ref == 'refs/heads/main' && github.event_name == 'push'
            run: docker push docker.pkg.github.com/messerli-wallace/doughflow/django:latest 
